Fixed log event call inside another logging event call, issue:
AttributeError: 'NoneType' object has no attribute 'write'
https://github.com/Preston-Landers/concurrent-log-handler/issues/4 (reverted from commit da4c6da01a340439bfd4a962654e3d4e0cb6860d)